export {
  EmailAccountService,
  ImapService,
  SmtpService,
  emailAccountService,
  imapService,
  smtpService,
  sanitizeHeaderValue,
  ForbiddenError,
  ImapConnectionError,
  NotFoundError,
  SmtpConnectionError,
} from './service.js';
export {
  AttachmentDtoSchema,
  CreateEmailAccountInputSchema,
  EmailAccountPublicDtoSchema,
  EmailAccountShareDtoSchema,
  EmailToActivityInputSchema,
  FolderDtoSchema,
  GetMessageQuerySchema,
  ListMessagesQuerySchema,
  MessageAddressDtoSchema,
  MessageDetailDtoSchema,
  MessageListDtoSchema,
  MessageListItemDtoSchema,
  SearchMessagesQuerySchema,
  SendEmailInputSchema,
  SetFlagsInputSchema,
  UpdateEmailAccountInputSchema,
  type AttachmentDto,
  type CreateEmailAccountInput,
  type EmailAccountPublicDto,
  type EmailToActivityInput,
  type FolderDto,
  type GetMessageQuery,
  type ListMessagesQuery,
  type MessageAddressDto,
  type MessageDetailDto,
  type MessageListDto,
  type MessageListItemDto,
  type SearchMessagesQuery,
  type SendEmailInput,
  type SetFlagsInput,
  type UpdateEmailAccountInput,
} from './schemas.js';
